/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_HelloJni */

#ifndef _Included_com_HelloJni
#define _Included_com_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_HelloJni
 * Method:    printJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_HelloJni_printJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
